version: "3.9"

services:
  db:
    image: postgres:15
    container_name: tasks_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: tasks_db
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./init_db.sql:/docker-entrypoint-initdb.d/init_db.sql

  web:
    build: .
    container_name: flask_web
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_NAME: tasks_db
      DB_USER: postgres
      DB_PASS: postgres
    depends_on:
      - db

volumes:
  db_data: