name: CI - Flask + PostgreSQL

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: tasks_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install requests

    - name: Wait for PostgreSQL
      run: |
        for i in {1..10}; do
          nc -zv localhost 5432 && break
          echo "Waiting for Postgres..."
          sleep 5
        done

    - name: Run Flask in background
      run: |
        nohup python app.py > flask.log 2>&1 &
        sleep 15
        echo "=== Flask Logs ==="
        cat flask.log

    - name: Test API endpoints
      run: |
        for i in {1..10}; do
          curl -X POST http://127.0.0.1:8080/add \
            -H "Content-Type: application/json" \
            -d '{"task":"CI/CD Test Task"}' && break
          echo "Retrying in 5s..."
          sleep 5
        done

        curl http://127.0.0.1:8080/tasks